### ISSUE TITLE
make  err

### ISSUE THREAD

**Issue by zchong1992** [bytedance/trace-noschedule#2]
In file included from include/asm-generic/percpu.h:6:0,
                 from ./arch/x86/include/asm/percpu.h:530,
                 from ./arch/x86/include/asm/current.h:5,
                 from ./arch/x86/include/asm/processor.h:15,
                 from ./arch/x86/include/asm/thread_info.h:22,
                 from include/linux/thread_info.h:54,
                 from include/linux/preempt.h:9,
                 from include/linux/spinlock.h:50,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/linux/ktime.h:24,
                 from include/linux/hrtimer.h:19,
                 from /home/xxx/code/trace-noschedule/trace_noschedule.c:13:
/home/xxx/code/trace-noschedule/trace_noschedule.c: In function ‘distribution_show’:
include/linux/percpu-defs.h:27:38: error: cast specifies array type
  const void __percpu *__vpp_verify = (typeof(ptr))NULL;  \
                                      ^
include/asm-generic/percpu.h:46:2: note: in expansion of macro ‘__verify_pcpu_ptr’
  __verify_pcpu_ptr((__p));     \
  ^
include/linux/percpu.h:149:31: note: in expansion of macro ‘SHIFT_PERCPU_PTR’
 #define per_cpu_ptr(ptr, cpu) SHIFT_PERCPU_PTR((ptr), per_cpu_offset((cpu)))
                               ^
/home/xxx/code/trace-noschedule/trace_noschedule.c:567:14: note: in expansion of macro ‘per_cpu_ptr’
   hist_cpu = per_cpu_ptr(stack_trace->hist, cpu);
              ^
/home/xxx/code/trace-noschedule/trace_noschedule.c: In function ‘trace_noschedule_init’:
/home/xxx/code/trace-noschedule/trace_noschedule.c:690:2: error: implicit declaration of function ‘for_each_kernel_tracepoint’ [-Werror=implicit-function-declaration]
  for_each_kernel_tracepoint(tracepoint_lookup, info);

在centos 7.2 内核 3.10.0-514.16.1.el7.x86_64下编译失败了

**Comment by smcdef** [comment]
> In file included from include/asm-generic/percpu.h:6:0,
> from ./arch/x86/include/asm/percpu.h:530,
> from ./arch/x86/include/asm/current.h:5,
> from ./arch/x86/include/asm/processor.h:15,
> from ./arch/x86/include/asm/thread_info.h:22,
> from include/linux/thread_info.h:54,
> from include/linux/preempt.h:9,
> from include/linux/spinlock.h:50,
> from include/linux/seqlock.h:35,
> from include/linux/time.h:5,
> from include/linux/ktime.h:24,
> from include/linux/hrtimer.h:19,
> from /home/xxx/code/trace-noschedule/trace_noschedule.c:13:
> /home/xxx/code/trace-noschedule/trace_noschedule.c: In function ‘distribution_show’:
> include/linux/percpu-defs.h:27:38: error: cast specifies array type
> const void __percpu *__vpp_verify = (typeof(ptr))NULL; 
> ^
> include/asm-generic/percpu.h:46:2: note: in expansion of macro ‘__verify_pcpu_ptr’
> __verify_pcpu_ptr((__p)); 
> ^
> include/linux/percpu.h:149:31: note: in expansion of macro ‘SHIFT_PERCPU_PTR’
> #define per_cpu_ptr(ptr, cpu) SHIFT_PERCPU_PTR((ptr), per_cpu_offset((cpu)))
> ^
> /home/xxx/code/trace-noschedule/trace_noschedule.c:567:14: note: in expansion of macro ‘per_cpu_ptr’
> hist_cpu = per_cpu_ptr(stack_trace->hist, cpu);
> ^
> /home/xxx/code/trace-noschedule/trace_noschedule.c: In function ‘trace_noschedule_init’:
> /home/xxx/code/trace-noschedule/trace_noschedule.c:690:2: error: implicit declaration of function ‘for_each_kernel_tracepoint’ [-Werror=implicit-function-declaration]
> for_each_kernel_tracepoint(tracepoint_lookup, info);
> 
> 在centos 7.2 内核 3.10.0-514.16.1.el7.x86_64下编译失败了

看起来是`for_each_kernel_tracepoint`没有定义，引入的patch在[这里](https://github.com/torvalds/linux/commit/de7b2973903c6cc50b31ee5682a69b2219b9919d)。我们需要在模块里面使用tracepoint，所以必须借助这个函数。或许你可以把这个patch backport回来。

**Comment by zchong1992** [comment]
ok 了解了，多谢
